version: "3.9"

services:
  todo:
    image: diamol/ch09-todo-list
    ports:
      - "8080:80"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
# todo

# your app

# exposes:

# /list

# /metrics

# prometheus

# reads prometheus.yml

# scrapes todo:80/metrics

# UI at :9090

# grafana

# UI at :3000

# you manually add Prometheus as datasource